### ISSUE TITLE
Rise up referral code

### ISSUE THREAD

**Issue by itsmaxjeffrey** [BarbossHack/RiseupVPN-OpenVPN#4]
My most sincere apologies for asking such a dumb question in the wrong place, but I would like to move from ProtonMail to RiseUp, since my data was breached due to lack of proper privacy with protonmail and I would like to use RiseUp instead. Can someone please help me here perhaps?

Thank you for your understanding.

Best Regards,

MJ

**Comment by BarbossHack** [comment]
Hi,

What do you mean by "my data was breached due to lack of proper privacy with protonmail" ? ProtonMail data (emails content) is encrypted and only your password can decrypt it. So what happens ? I'm curious !

Anyway, RiseupMail is not as good as ProtonMail for email encryption. Your data is also encrypted with your password, but your password is sent in clear to the server to be able to decrypt your emails server-side (using TREES dovecot plugin). Technically, Riseup could read all your emails without you noticing it...
